//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : Autofacdemo
	/// Data Source    : 127.0.01
	/// Server Version : 5.5.5-10.1.37-MariaDB
	/// </summary>
	public partial class AutofacdemoDB : LinqToDB.Data.DataConnection
	{
		public ITable<Test> Tests { get { return this.GetTable<Test>(); } }

		public AutofacdemoDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AutofacdemoDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("test")]
	public partial class Test
	{
		[Column("id"),   NotNull    ] public int    Id   { get; set; } // int(11)
		[Column("name"),    Nullable] public string Name { get; set; } // varchar(50)
	}
}
